# !!!!!! You need to rename this file to secrets.toml and add username and passcode below !!!!!!

# Credentials for WebDAV file storage such as SwitchDrive
[webdav]
base_url = "https://drive.switch.ch/index.php/settings/personal?sectionid=security"
username = "carmen.hurschler@gmail.com"
password = "NXUAY-ADCLM-SUVMK-RIUAU"
